name: Build and Publish Docker Images

on:
  pull_request:
    branches: [ master ]

jobs:

  check:
    name: Check changed files
    outputs:
      dockerfile: ${{ steps.git_diff.outputs.dockerfile }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check modified files
        id: git_diff
        run: |
            echo "=============== list modified files ==============="
            git diff --name-only HEAD^ HEAD
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == Dockerfile ]]; then
                echo "::set-output name=dockerfile::true"
              fi
            done < files.txt

  build:
    needs: check
    if: needs.check.outputs.dockerfile == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build image
      run: docker build . --file ./Dockerfile --tag terraform:$(date +%s)
